server:
  port: 8085
spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
logging:
  level:
    com.example.notificationservice: INFO
    org.springframework: WARN