replicaCount: 3
image:
  repository: <account-id>.dkr.ecr.us-east-1.amazonaws.com/booking-service
  tag: latest
  pullPolicy: Always
service:
  port: 8084
resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
hpa:
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilization: 70
env:
  SPRING_DATASOURCE_USERNAME: admin