CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    show_id BIGINT,
    booking_time TIMESTAMP,
    total_amount DECIMAL(10, 2),
    status INTEGER
);

CREATE TABLE IF NOT EXISTS booked_seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT,
    seat_id BIGINT,
    FOREIGN KEY (booking_id) REFERENCES bookings(id)
);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT,
    amount DECIMAL(10, 2),
    payment_time TIMESTAMP,
    status INTEGER,
    FOREIGN KEY (booking_id) REFERENCES bookings(id)
);

INSERT INTO bookings (user_id, show_id, booking_time, total_amount, status)
VALUES (1, 1, '2025-05-13 15:30:00', 20.00, 1);
INSERT INTO booked_seats (booking_id, seat_id) VALUES (1, 1);
INSERT INTO payments (booking_id, amount, payment_time, status)
VALUES (1, 20.00, '2025-05-13 15:31:00', 1);