apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: movie-ticket-booking
type: Opaque
data:
  postgres-user-password: c2VjdXJlLXBhc3N3b3Jk # base64: secure-password
  postgres-movie-password: c2VjdXJlLXBhc3N3b3Jk
  postgres-theatre-password: c2VjdXJlLXBhc3N3b3Jk
  postgres-booking-password: c2VjdXJlLXBhc3N3b3Jk
  postgres-subscription-password: c2VjdXJlLXBhc3N3b3Jk
  postgres-ad-password: c2VjdXJlLXBhc3N3b3Jk
  stripe-api-key: c2stc2VjdXJlLWtleQ== # base64: sk-secure-key
  paytm-merchant-id: c2VjdXJlLW1lcmNoYW50LWlk # base64: secure-merchant-id
  jasypt-encryptor-password: c2VjdXJlLWVuY3J5cHRpb24ta2V5 # base64: secure-encryption-key
  keycloak-password: c2VjdXJlLWtleWNsb2Fr # base64: secure-keycloak