CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20)
);

INSERT INTO users (name, email, phone_number) VALUES ('Rahul', 'rahul@example.com', '1234567890');