apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  postgres-user-password: {{ .Values.secrets.postgresUserPassword | b64enc }}
  postgres-movie-password: {{ .Values.secrets.postgresMoviePassword | b64enc }}
  postgres-theatre-password: {{ .Values.secrets.postgresTheatrePassword | b64enc }}
  postgres-booking-password: {{ .Values.secrets.postgresBookingPassword | b64enc }}
  postgres-subscription-password: {{ .Values.secrets.postgresSubscriptionPassword | b64enc }}
  postgres-ad-password: {{ .Values.secrets.postgresAdPassword | b64enc }}
  stripe-api-key: {{ .Values.secrets.stripeApiKey | b64enc }}
  paytm-merchant-id: {{ .Values.secrets.paytmMerchantId | b64enc }}
  jasypt-encryptor-password: {{ .Values.secrets.jasyptEncryptorPassword | b64enc }}
  keycloak-password: {{ .Values.secrets.keycloakPassword | b64enc }}