CREATE TABLE IF NOT EXISTS city (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    state VARCHAR(100),
    zip_code VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS theatres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city_id BIGINT,
    FOREIGN KEY (city_id) REFERENCES city(id)
);

CREATE TABLE IF NOT EXISTS screens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theatre_id BIGINT,
    name VARCHAR(255) NOT NULL,
    total_seats INTEGER,
    FOREIGN KEY (theatre_id) REFERENCES theatres(id)
);

CREATE TABLE IF NOT EXISTS shows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT,
    screen_id BIGINT,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    status INTEGER,
    FOREIGN KEY (screen_id) REFERENCES screens(id)
);

CREATE TABLE IF NOT EXISTS seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id BIGINT,
    seat_number VARCHAR(10),
    FOREIGN KEY (screen_id) REFERENCES screens(id)
);

INSERT INTO city (name, state, zip_code) VALUES ('Jalandhar', 'Punjab', '144008');
INSERT INTO theatres (name, city_id) VALUES ('PVR', 1);
INSERT INTO screens (theatre_id, name, total_seats) VALUES (1, 'Screen 1', 100);
INSERT INTO shows (movie_id, screen_id, start_time, end_time, status)
VALUES (1, 1, '2025-05-13 15:00:00', '2025-05-13 17:00:00', 1);
INSERT INTO seats (screen_id, seat_number) VALUES (1, 'A1'), (1, 'A2'), (1, 'A3');