CREATE TABLE IF NOT EXISTS movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    language VARCHAR(50),
    description TEXT,
    duration INTEGER,
    release_date TIMESTAMP,
    country VARCHAR(100),
    genre VARCHAR(50)
);

INSERT INTO movies (title, language, description, duration, release_date, country, genre)
VALUES ('Border', 'Hindi', 'India Pakistan war', 120, '2025-05-01 00:00:00', 'India', 'Action');